## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import itertools


from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" # type: ignore

## Import Paths

In [2]:
from pathlib import Path
from utils.path_loader import load_paths
paths = load_paths()

PROJECT_ROOT = paths["project_root"]
# print(PROJECT_ROOT)

## Import Functions

In [3]:
from train_yolo.functions.yolo_results import collect_all_models

## Load the Data

In [4]:
df_models = collect_all_models()

print("Número de runs encontrados:", len(df_models))
df_models.head()

Número de runs encontrados: 21

,yolo_version,task,train_run,epochs_config,batch_config,best_epoch,mAP50,mAP50-95,precision,recall,val_box_loss,val_cls_loss,val_dfl_loss,has_best_weights,run_path
0,yolo11m,text-photo,train-150e8b,150,8,137,0.96288,0.88083,0.93996,0.94068,0.63244,0.40604,0.94324,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
1,yolo11m,text-photo,train-150e4b,150,4,140,0.95996,0.87510,0.93518,0.94326,0.63579,0.38550,0.93975,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
2,yolo11s,text-photo,train-150e2b,150,2,130,0.96380,0.87301,0.93939,0.94562,0.61990,0.42465,0.91354,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
3,yolo11s,text-photo,train-150e6b,150,6,133,0.95890,0.87256,0.92871,0.94878,0.63772,0.42279,0.92648,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
4,yolo11s,text-photo,train-150e14b,150,14,114,0.96047,0.87143,0.94053,0.93488,0.64074,0.41563,0.92860,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...

## Explore the Data

In [5]:
df_sorted = df_models.sort_values("mAP50-95", ascending=False)

df_sorted

,yolo_version,task,train_run,epochs_config,batch_config,best_epoch,mAP50,mAP50-95,precision,recall,val_box_loss,val_cls_loss,val_dfl_loss,has_best_weights,run_path
0,yolo11m,text-photo,train-150e8b,150,8,137,0.96288,0.88083,0.93996,0.94068,0.63244,0.40604,0.94324,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
1,yolo11m,text-photo,train-150e4b,150,4,140,0.95996,0.87510,0.93518,0.94326,0.63579,0.38550,0.93975,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
2,yolo11s,text-photo,train-150e2b,150,2,130,0.96380,0.87301,0.93939,0.94562,0.61990,0.42465,0.91354,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
3,yolo11s,text-photo,train-150e6b,150,6,133,0.95890,0.87256,0.92871,0.94878,0.63772,0.42279,0.92648,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
4,yolo11s,text-photo,train-150e14b,150,14,114,0.96047,0.87143,0.94053,0.93488,0.64074,0.41563,0.92860,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
5,yolo11s,text-photo,train-150e5b,150,5,117,0.96036,0.87128,0.93106,0.93994,0.63134,0.42985,0.91753,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
6,yolo11s,text-photo,train-150e4b,150,4,135,0.95843,0.87079,0.93390,0.95063,0.62740,0.40453,0.91603,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
7,yolo11s,text-photo,train-150e3b,150,3,135,0.95861,0.86808,0.93967,0.94819,0.62629,0.40905,0.91482,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
8,yolo11s,text-photo,train-150e12b,150,12,130,0.95778,0.86745,0.92933,0.94657,0.64624,0.41473,0.92925,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
9,yolo11s,text-photo,train-150e11b,150,11,117,0.95745,0.86728,0.94080,0.93914,0.64704,0.41271,0.93839,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
10,yolo26s,text-photo,train-150e4b,150,4,98,0.95998,0.86721,0.91895,0.94110,0.65562,0.48420,0.00604,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
11,yolo26s,text-photo,train-150e8b,150,8,111,0.95758,0.86676,0.93220,0.93017,0.66487,0.45587,0.00621,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
12,yolo11s,text-photo,train-150e8b,150,8,69,0.96007,0.86504,0.92560,0.94386,0.62551,0.44502,0.91580,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
13,yolo11s,text-photo,train-150e7b,150,7,122,0.95383,0.86491,0.92014,0.95578,0.64016,0.42323,0.92433,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
14,yolo11s,text-photo,train-150e9b,150,9,63,0.95891,0.86375,0.93309,0.94181,0.63726,0.43283,0.92164,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
15,yolov8s,text-photo,train-150e4b,150,4,113,0.95552,0.86371,0.92931,0.93589,0.62814,0.43453,0.92278,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
16,yolo11s,text-photo,train-150e10b,150,10,115,0.95259,0.86247,0.93835,0.93982,0.65023,0.41316,0.92823,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
17,yolo11s,text-photo,train-150e16b,150,16,109,0.95412,0.86216,0.93238,0.93636,0.64722,0.42148,0.92884,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
18,yolo11s,text-photo,train-150e20b,150,20,52,0.95971,0.86206,0.92431,0.94031,0.63647,0.44914,0.92972,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
19,yolov8s,text-photo,train-150e8b,150,8,93,0.95999,0.86062,0.92113,0.93869,0.65075,0.45245,0.93759,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...
20,yolo11s,skill_table,train-150e4b,150,4,11,0.90056,0.63159,0.83295,0.81818,0.87663,0.83648,0.88664,True,C:\Users\danie\Desktop\My_Things\Hobbies\VSCOD...

## Graphics